package sulfur

const ExportOrgSubdomainTakeovers = "/export/org/{org_id}/takeovers"
const ExportOrgBadCertificate = "/export/org/{org_id}/bad_certificates"
const ImportDNSRecordsPath = "/consume/dns_records"
const ImportDomainAndResolvePath = "/consume/domains/resolve"
const ImportOrgRootDomainsPath = "/import/org/{org_id}/assets/root_domains"
const ImportOrgIPAddressesPath = "/import/org/{org_id}/assets/ip_addresses"
const AuthUserPath = "/api/collections/users/auth-with-password"
const AuthSuperUserPath = "/api/collections/_superusers/auth-with-password"
const RootDomainsPath = "/api/collections/root_domains/records"
const OrgDomainsPath = "/api/collections/org_domains/records"
const OrgIPAddressesPath = "/api/collections/org_ip_addresses/records"
const OrganizationsPath = "/api/collections/organizations/records"
const DNSRecordsPath = "/api/collections/dns_records/records"
