package sulfur

const ExportOrgSubdomainTakeoversPath = "/export/org/{org_id}/takeovers"
const ExportOrgBadCertificatePath = "/export/org/{org_id}/bad_certificates"
const ImportDNSRecordsPath = "/consume/dns_records"
const ImportDomainAndResolvePath = "/consume/domains/resolve"
const ImportExternalReferencesPath = "/import/external_references"
const ImportOrgRootDomainsPath = "/import/org/{org_id}/assets/root_domains"
const ImportOrgIPAddressesPath = "/import/org/{org_id}/assets/ip_addresses"
const AuthUserPath = "/api/collections/users/auth-with-password"
const AuthSuperUserPath = "/api/collections/_superusers/auth-with-password"
const RootDomainsPath = "/api/collections/root_domains/records"
const OrgDomainsPath = "/api/collections/org_domains/records"
const OrgIPPortsPath = "/api/collections/org_ip_ports/records"
const OrgIPAddressesPath = "/api/collections/org_ip_addresses/records"
const OrganizationsPath = "/api/collections/organizations/records"
const DNSRecordsPath = "/api/collections/dns_records/records"
const ExternalReferencesPath = "/api/collections/external_references/records"
